import { describe, expect, it } from "vitest";
import {
  buildColumnChunks,
  exportToCsv,
  exportToExcel,
  sanitizePdfText,
} from "@/lib/utils/report-export";

const sampleOptions = {
  title: "Student Report",
  subtitle: "Weekly period",
  companyName: "Lakshya International Edwise",
  tagline: "Your go-to education loan expert",
  generatedBy: "Kavinkumar K",
  generatedAt: new Date("2024-06-25T12:52:00"),
};

const sampleData = [
  {
    "Student ID": "STU-001",
    Status: "loan_disbursed",
    "Loan Sanctioned": "₹5,00,000",
  },
];

describe("report-export", () => {
  it("replaces rupee symbol with Rs. for PDF-safe output", () => {
    expect(sanitizePdfText("₹22,50,000")).toBe("Rs. 22,50,000");
  });

  it("strips unsupported characters from PDF text", () => {
    expect(sanitizePdfText("Test — value")).toBe("Test - value");
  });

  it("keeps narrow reports in a single table", () => {
    const columns = ["Name", "Status", "Amount"];
    expect(buildColumnChunks(columns)).toEqual([columns]);
  });

  it("chunks wide student reports with pinned identity columns", () => {
    const columns = [
      "Student ID",
      "Full Name",
      "Email",
      "Phone",
      "College",
      "Degree",
      "Status",
      "Bank",
      "LAN",
      "Notes",
      "Created On",
    ];
    const chunks = buildColumnChunks(columns);
    expect(chunks.length).toBeGreaterThan(1);
    expect(chunks[0].slice(0, 2)).toEqual(["Student ID", "Full Name"]);
    expect(chunks.every((chunk) => chunk.length <= 9)).toBe(true);
  });

  it("builds branded CSV with metadata and UTF-8 BOM", () => {
    const csv = exportToCsv(sampleData, sampleOptions);
    expect(csv.startsWith("\uFEFF")).toBe(true);
    expect(csv).toContain("Lakshya International Edwise");
    expect(csv).toContain("Generated by,Kavinkumar K");
    expect(csv).toContain("Student ID,Status,Loan Sanctioned");
    expect(csv).toContain('STU-001,Loan Disbursed,"Rs. 5,00,000"');
    expect(csv).toContain("Confidential — Lakshya International Edwise");
  });

  it("builds branded Excel workbook buffer", () => {
    const buffer = exportToExcel(sampleData, sampleOptions);
    expect(buffer.length).toBeGreaterThan(0);
    expect(buffer.subarray(0, 2).toString("utf8")).toBe("PK");
  });
});
